### PR TITLE
Basic memory management

### LINKED ISSUE #5: Kernel malloc.
Write a malloc to be used in kernel space. There's a bunch of ways to do this and it might be worthwhile to have multiple implementations; it'd be an easy feature to implement.

There's a reference on [OSDev](https://wiki.osdev.org/Writing_a_memory_manager), but there's significant resources elsewhere because you often roll a specialized malloc in userspace (jemalloc, etc.).

This issue is likely tightly coupled with #4.

### PR DESCRIPTION
**Pull request by LaneDoesThings**
Will eventually be a very poor implementation of a memory manager.
Probably using flat memory.
might close #5

### CODE REVIEW

**Comment by jonesz** [comment]
So Britton has got paging enabled -- that is we can bind a virtual memory space to anywhere we want in the physical memory.

So not to butt in, but this last commit it seems like you're fetching in the memory information from the bootloader -- which we do need (I'm musing about this in Britton's #18 before I looked over here). We do need that, but I don't know if you need it for kmalloc impl.

Think of kmalloc as a structure knowing that from 0xFA000 to 0xFF000 the memory can be doled out as it wishes, so calls to kmalloc(variable sized object)/free(mem addr) can dynamically allocate this mem. You might need to attack it from a more abstract position.

**Comment by jonesz** [comment]
If you want to pull in the multiboot information that I believe provides information about the memory mapped I/O, what can and can't be used, etc., I think you're doing something different from #5. That's perfectly fine because I'm actually interested in that exact information. I just want to make sure you don't waste your effort on something you don't need to and have the correct problem space in mind.

**Comment by LaneDoesThings** [comment]
Ok, I think I understand what you are saying and how to proceed. I was a little lost at first so I just went to the next steps section in osdev and under memory management grabbing the memory table was the first thing listed so I just started there. I will start working on a more abstract kmalloc function.

**Comment by LaneDoesThings** [comment]
Can someone look at this and see if I am heading in the right direction at all. I'm following the tutorial at [OSDev](https://wiki.osdev.org/Writing_a_memory_manager) and using [liballoc](https://github.com/blanham/liballoc/) as a guide.

**Pull request merged**
